pub fn UnrecoverableErrors() {
    // println!("First line code to execute");
    // panic!("Code Panic here!");
    // println!("Unreachable");     // unreachable statement -->> Since code panic above

    // let arr = vec![1, 2, 3];
    // let er = arr[9];             // "PANIC" -->> Try to access memory "OUT OF BOUND"
}